features: ['ELEVATION', 'CLDD', 'DX70', 'EMNT', 'EMXT', 'HTDD']
correlation_threshold: 0.6
predict_features: ['TMIN', 'TMAX', 'TAVG']
train: 'data/train.csv'
test: 'data/test.csv'
weight_path: 'src_1/weights/'
correlation_csv_path: 'src_1/correlation.csv'