name: notebook compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo pip install -r REQUIREMENTS.txt
    - name: Testing
      run: pytest